### ISSUE TITLE
Modeling your outcome set in the SSVC project

### ISSUE THREAD

**Issue by ahouseholder** [theparanoids/PrioritizedRiskRemediation#1]
Hi, I'm one of the SSVC maintainers. Just wanted to make you aware of (and invite your feedback on) https://github.com/CERTCC/SSVC/issues/358 where we're trying to capture the essence of the 6-level outcome set you have modeled in this project.

**Comment by Crashedmind** [comment]
'responded on https://github.com/CERTCC/SSVC/issues/358
